---
- name: Add non-free debian repository
  apt_repository:
    repo: deb http://deb.debian.org/debian bullseye contrib non-free
    state: present
    update_cache: yes

- name: Install driver for BCM43142 wireless chipset
  apt:
    name: broadcom-sta-dkms
    state: present
