---
- name: Add a user for the mediacenter
  user:
    name: mediacenter
    comment: Mediacenter
    groups: cdrom,floppy,audio,video,plugdev,netdev,bluetooth,lpadmin,scanner
    append: yes

- name: Install `kodi`
  apt:
    name: kodi
    state: present
    install_recommends: yes
    update_cache: yes
    cache_valid_time: 3600

- name: Set `kodi` as default session for `mediacenter`
  copy:
    src: mediacenter-session
    dest: /var/lib/AccountsService/users/mediacenter
    owner: root
    group: root
    mode: 644

- name: Skip login screen
  lineinfile:
    path: /etc/gdm3/daemon.conf
    regexp: '^#?\s*AutomaticLoginEnable\s*='
    line: AutomaticLoginEnable = true

- name: GDM should always login `mediacenter`
  lineinfile:
    path: /etc/gdm3/daemon.conf
    regexp: '^#?\s*AutomaticLogin\s*='
    line: AutomaticLogin = mediacenter

- name: Add non-free debian repository
  apt_repository:
    repo: deb http://deb.debian.org/debian bullseye contrib non-free
    state: present
    update_cache: yes

- name: Check if `i386` architecture is already enabled
  shell: dpkg --print-foreign-architectures
  register: i386_result

- name: Enable Multi-Arch
  shell: dpkg --add-architecture i386
  when: not i386_result.stdout is search('i386')

- name: Update cache
  apt:
    update_cache: yes
  when: not i386_result.stdout is search('i386')

- name: Install `steam`
  apt:
    name: steam
    state: present

- name: Install packages the debian wiki recommends for `steam`
  apt:
    pkg:
    - mesa-vulkan-drivers
    - libglx-mesa0:i386
    - mesa-vulkan-drivers:i386
    - libgl1-mesa-dri:i386
    state: present
